package Apk;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class Frame_Register extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Register
     */
    public Frame_Register() {
        initComponents();

        SignIn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                // Membuka JFrame Login
                Frame_Login Frame_LoginFrame = new Frame_Login();
                Frame_LoginFrame.setVisible(true);
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ikon_NamaLengkap = new javax.swing.JLabel();
        Ikon_NoTelp = new javax.swing.JLabel();
        Ikon_Username = new javax.swing.JLabel();
        Ikon_Password = new javax.swing.JLabel();
        Text_Password = new javax.swing.JTextField();
        Tombol_Register = new javax.swing.JButton();
        SignIn = new javax.swing.JLabel();
        Text_Username = new javax.swing.JTextField();
        Text_No_Telp = new javax.swing.JTextField();
        Text_Nama_Lengkap = new javax.swing.JTextField();
        Frame_Register = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ikon_NamaLengkap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Apk/Kumpulan_Gambar/Name Tag.png"))); // NOI18N
        getContentPane().add(Ikon_NamaLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 30, 30));

        Ikon_NoTelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Apk/Kumpulan_Gambar/Phone.png"))); // NOI18N
        getContentPane().add(Ikon_NoTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 30, 30));

        Ikon_Username.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Apk/Kumpulan_Gambar/Male User_1.png"))); // NOI18N
        getContentPane().add(Ikon_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 30, 30));

        Ikon_Password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Apk/Kumpulan_Gambar/Password_1.png"))); // NOI18N
        getContentPane().add(Ikon_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, -1, 30));

        Text_Password.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        Text_Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Text_Password.setText("Password");
        Text_Password.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Text_Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Text_PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Text_PasswordFocusLost(evt);
            }
        });
        getContentPane().add(Text_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 200, 30));

        Tombol_Register.setBackground(new java.awt.Color(0, 0, 204));
        Tombol_Register.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        Tombol_Register.setForeground(new java.awt.Color(255, 255, 255));
        Tombol_Register.setText("Register");
        getContentPane().add(Tombol_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 120, 30));

        SignIn.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        SignIn.setForeground(new java.awt.Color(255, 255, 255));
        SignIn.setText("Sign In");
        SignIn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignInMouseClicked(evt);
            }
        });
        getContentPane().add(SignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 80, -1));

        Text_Username.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        Text_Username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Text_Username.setText("Username");
        Text_Username.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Text_Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Text_UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Text_UsernameFocusLost(evt);
            }
        });
        getContentPane().add(Text_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 200, 30));

        Text_No_Telp.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        Text_No_Telp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Text_No_Telp.setText("No Telp");
        Text_No_Telp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Text_No_Telp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Text_No_TelpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Text_No_TelpFocusLost(evt);
            }
        });
        getContentPane().add(Text_No_Telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 200, 30));

        Text_Nama_Lengkap.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        Text_Nama_Lengkap.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Text_Nama_Lengkap.setText("Nama Lengkap");
        Text_Nama_Lengkap.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Text_Nama_Lengkap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Text_Nama_LengkapFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Text_Nama_LengkapFocusLost(evt);
            }
        });
        getContentPane().add(Text_Nama_Lengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 200, 30));

        Frame_Register.setForeground(new java.awt.Color(255, 255, 255));
        Frame_Register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Apk/Kumpulan_Gambar/Frame_Register.png"))); // NOI18N
        Frame_Register.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        getContentPane().add(Frame_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignInMouseClicked

    }//GEN-LAST:event_SignInMouseClicked

    private void Text_Nama_LengkapFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Text_Nama_LengkapFocusGained
        // TODO add your handling code here:
        String fullname = Text_Nama_Lengkap.getText();
        if (fullname.equals("Nama Lengkap")) {
            Text_Nama_Lengkap.setText("");
        }
    }//GEN-LAST:event_Text_Nama_LengkapFocusGained

    private void Text_Nama_LengkapFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Text_Nama_LengkapFocusLost
        // TODO add your handling code here:
        String fullname = Text_Nama_Lengkap.getText();
        if (fullname.equals("") || fullname.equals("Nama Lengkap")) {
            Text_Nama_Lengkap.setText("Nama Lengkap");
        }
    }//GEN-LAST:event_Text_Nama_LengkapFocusLost

    private void Text_No_TelpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Text_No_TelpFocusGained
        // TODO add your handling code here:
        String telp = Text_No_Telp.getText();
        if (telp.equals("No Telp")) {
            Text_No_Telp.setText("");
        }
    }//GEN-LAST:event_Text_No_TelpFocusGained

    private void Text_No_TelpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Text_No_TelpFocusLost
        // TODO add your handling code here:
        String telp = Text_No_Telp.getText();
        if (telp.equals("") || telp.equals("No Telp")) {
            Text_No_Telp.setText("No Telp");
        }
    }//GEN-LAST:event_Text_No_TelpFocusLost

    private void Text_UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Text_UsernameFocusGained
        // TODO add your handling code here:
        String name = Text_Username.getText();
        if (name.equals("Username")) {
            Text_Username.setText("");
        }
    }//GEN-LAST:event_Text_UsernameFocusGained

    private void Text_UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Text_UsernameFocusLost
        // TODO add your handling code here:
        String name = Text_Username.getText();
        if (name.equals("") || name.equals("Username")) {
            Text_Username.setText("Username");
        }
    }//GEN-LAST:event_Text_UsernameFocusLost

    private void Text_PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Text_PasswordFocusGained
        // TODO add your handling code here:
        String pass = Text_Password.getText();
        if (pass.equals("Password")) {
            Text_Password.setText("");
        }
    }//GEN-LAST:event_Text_PasswordFocusGained

    private void Text_PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Text_PasswordFocusLost
        // TODO add your handling code here:
        String pass = Text_Password.getText();
        if (pass.equals("") || pass.equals("Password")) {
            Text_Password.setText("Password");
        }
    }//GEN-LAST:event_Text_PasswordFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Frame_Register;
    private javax.swing.JLabel Ikon_NamaLengkap;
    private javax.swing.JLabel Ikon_NoTelp;
    private javax.swing.JLabel Ikon_Password;
    private javax.swing.JLabel Ikon_Username;
    private javax.swing.JLabel SignIn;
    private javax.swing.JTextField Text_Nama_Lengkap;
    private javax.swing.JTextField Text_No_Telp;
    private javax.swing.JTextField Text_Password;
    private javax.swing.JTextField Text_Username;
    private javax.swing.JButton Tombol_Register;
    // End of variables declaration//GEN-END:variables
}
