/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Apk;

import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author HP
 */
public class Frame_Login extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Login
     */
    public Frame_Login() {
        initComponents();
        
         SignUp.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                // Membuka JFrame Login
                Frame_Register Frame_RegisterFrame = new Frame_Register();
                Frame_RegisterFrame.setVisible(true);
                dispose();
            }
        });
    }

    void bersih (){
        Text_Username.setText("Username");
        Text_Password.setText("Password");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ikon_Username = new javax.swing.JLabel();
        Ikon_Password = new javax.swing.JLabel();
        Tombol_SignIn = new javax.swing.JButton();
        Text_Username = new javax.swing.JTextField();
        SignUp = new javax.swing.JLabel();
        Text_Password = new javax.swing.JTextField();
        Check_ShowPassword = new javax.swing.JCheckBox();
        Frame_Login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ikon_Username.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Apk/Kumpulan_Gambar/Male User_1.png"))); // NOI18N
        getContentPane().add(Ikon_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 220, 30, 50));

        Ikon_Password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Apk/Kumpulan_Gambar/Password_1.png"))); // NOI18N
        getContentPane().add(Ikon_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 280, -1, 30));

        Tombol_SignIn.setBackground(new java.awt.Color(0, 102, 153));
        Tombol_SignIn.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        Tombol_SignIn.setForeground(new java.awt.Color(255, 255, 255));
        Tombol_SignIn.setText("Sign In");
        Tombol_SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tombol_SignInActionPerformed(evt);
            }
        });
        getContentPane().add(Tombol_SignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 90, 30));

        Text_Username.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        Text_Username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Text_Username.setText("Username");
        Text_Username.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Text_Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Text_UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Text_UsernameFocusLost(evt);
            }
        });
        getContentPane().add(Text_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 210, 30));

        SignUp.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        SignUp.setForeground(new java.awt.Color(255, 255, 255));
        SignUp.setText("Sign Up");
        getContentPane().add(SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, 80, 30));

        Text_Password.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        Text_Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Text_Password.setText("Password");
        Text_Password.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Text_Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Text_PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Text_PasswordFocusLost(evt);
            }
        });
        getContentPane().add(Text_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 210, 30));

        Check_ShowPassword.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        Check_ShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        Check_ShowPassword.setText("Show Password");
        Check_ShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check_ShowPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Check_ShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, -1));

        Frame_Login.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        Frame_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Apk/Kumpulan_Gambar/Frame_Login.png"))); // NOI18N
        Frame_Login.setText("Password");
        Frame_Login.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(Frame_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tombol_SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tombol_SignInActionPerformed

    }//GEN-LAST:event_Tombol_SignInActionPerformed

    private void Text_UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Text_UsernameFocusGained
        // TODO add your handling code here:
        String name = Text_Username.getText();
        if(name.equals("Username")) {
            Text_Username.setText("");
        }
    }//GEN-LAST:event_Text_UsernameFocusGained

    private void Text_UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Text_UsernameFocusLost
        // TODO add your handling code here:
        String name = Text_Username.getText();
        if(name.equals("")||name.equals("Username")) {
            Text_Username.setText("Username");
        }
    }//GEN-LAST:event_Text_UsernameFocusLost

    private void Text_PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Text_PasswordFocusGained
        // TODO add your handling code here:
        String pass = Text_Password.getText();
        if(pass.equals("Password")) {
            Text_Password.setText("");
        }
    }//GEN-LAST:event_Text_PasswordFocusGained

    private void Text_PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Text_PasswordFocusLost
        // TODO add your handling code here:
        String pass = Text_Password.getText();
        if(pass.equals("")||pass.equals("Password")) {
            Text_Password.setText("Password");
        }
    }//GEN-LAST:event_Text_PasswordFocusLost

    private void Check_ShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check_ShowPasswordActionPerformed
        // TODO add your handling code here:
       // if(Check_ShowPassword.isSelected()) {
           Text_Password.setEchoChar((char)0); 
        }
        else {
            Text_Password.setEchoChar('*');
        }
    }//GEN-LAST:event_Check_ShowPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Check_ShowPassword;
    private javax.swing.JLabel Frame_Login;
    private javax.swing.JLabel Ikon_Password;
    private javax.swing.JLabel Ikon_Username;
    private javax.swing.JLabel SignUp;
    private javax.swing.JTextField Text_Password;
    private javax.swing.JTextField Text_Username;
    private javax.swing.JButton Tombol_SignIn;
    // End of variables declaration//GEN-END:variables
}
